### ISSUE TITLE
isEdge check is coercing a function

### ISSUE THREAD

**Issue by DavidReinberger** [flexdinesh/react-render-in-browser#1]
Are you sure this is correct? `isIE` is a function therefore at runtime will coerce  to a true because it is declared, shouldn't it run the function?

Did not test it though just was curios how are you doing the browser detection, GJ!

https://github.com/flexdinesh/react-render-in-browser/blob/928e3ed73cbefbd127bd322a88341fd6117e40b2/src/RenderInBrowser/browser-check.js#L30

**Comment by flexdinesh** [comment]
@DavidReinberger Good catch. I'm going to fix that. 

I bit of history. I got the source to detect browsers from [here](https://stackoverflow.com/a/9851769/3626796). I converted them all to methods but missed out this cross evaluation in IE. Thanks for catching this. You are amazing!

**Comment by DavidReinberger** [comment]
`isBlink` is also using the "legacy" method.

**Comment by flexdinesh** [comment]
`f322b4eb14ae6918ec362216525afb15ec604f5a` fixes this issue
