### ISSUE TITLE
Chromium edge detected as chrome

### ISSUE THREAD

**Issue by peterj35** [flexdinesh/react-render-in-browser#4]
Hi, it looks like chromium edge is detected as chrome, which is likely incorrect. Thinking [this UA check](https://stackoverflow.com/questions/60185295/what-is-the-correct-way-to-detect-new-microsoft-edge-v80-blink-via-javascript) can be added to check for chromium edge

**Comment by flexdinesh** [comment]
Thanks @peterj35. Do you want to PR it in?

**Comment by peterj35** [comment]
Yup, @flexdinesh : https://github.com/flexdinesh/react-render-in-browser/pull/5
